"""empty message

Revision ID: be4cc3a638c6
Revises: 2a7a36bd72f6
Create Date: 2025-05-23 04:45:22.247638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4cc3a638c6'
down_revision = '2a7a36bd72f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('altura', sa.String(length=20), nullable=False),
    sa.Column('peso', sa.String(length=20), nullable=False),
    sa.Column('genero', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('periodo_rotacion', sa.String(length=100), nullable=False),
    sa.Column('periodo_orbital', sa.String(length=100), nullable=False),
    sa.Column('terreno', sa.String(length=50), nullable=False),
    sa.Column('diametro', sa.String(length=50), nullable=False),
    sa.Column('clima', sa.String(length=100), nullable=False),
    sa.Column('gravedad', sa.String(length=100), nullable=False),
    sa.Column('poblacion', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('contraseña', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('fabricante', sa.String(length=120), nullable=False),
    sa.Column('costo_en_creditos', sa.String(length=50), nullable=False),
    sa.Column('longitud', sa.String(length=50), nullable=False),
    sa.Column('tripulacion', sa.String(length=50), nullable=False),
    sa.Column('pasajeros', sa.String(length=50), nullable=False),
    sa.Column('capacidad_de_carga', sa.String(length=50), nullable=False),
    sa.Column('consumibles', sa.String(length=50), nullable=False),
    sa.Column('clase', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('vehicles')
    op.drop_table('favorites')
    op.drop_table('people')
    op.drop_table('user')
    op.drop_table('planets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('climate', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('population', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('diameter', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planets_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('height', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('mass', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='people_pkey')
    )
    op.create_table('favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='favorites_pkey')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('manufacturer', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('cost_in_credits', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('length', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('crew', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('passengers', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='vehicles_pkey')
    )
    op.drop_table('vehiculos')
    op.drop_table('usuario')
    op.drop_table('planetas')
    op.drop_table('personas')
    op.drop_table('favoritos')
    # ### end Alembic commands ###
